### PR TITLE
Ht1/zhabko

### PR DESCRIPTION
**Pull request by AlexeyZhabko**

### CODE REVIEW

**Comment by AlexOreshkevich** [comment]
@AlexeyZhabko please fix static code analysis issues, for example: https://github.com/AlexOreshkevich/M-JC1-83-21/pull/9/checks?check_run_id=3265936044

You can found them by pressing blue Details link to the right.

**Review by AlexOreshkevich — CHANGES_REQUESTED** [review]
Please fix all build checks first

**Comment by AlexeyZhabko** [comment]
My Travis CI builds fail. How can get information about errors? In details and on Travis site i see only that my builds failed.

**Comment by AlexOreshkevich** [comment]
> My Travis CI builds fail. How can get information about errors? In details and on Travis site i see only that my builds failed.

Try https://app.travis-ci.com/github/AlexOreshkevich/M-JC1-83-21/builds/234761708

JFYI I'm going to fix your branch build now

**Review by AlexOreshkevich — APPROVED** [review]
lgtm

to improve your mark, add unit tests

**Review by AlexOreshkevich — APPROVED** [review]
lgtm, unit tests are missing

**Pull request closed without merging**
